Algoritmo "horas cumprimento"

Var
horas :  inteiro


Inicio
Escreva ("Informe que horas são: ")
leia (horas)

escolha horas
        caso 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11
        Escreva ("Bom dia!")
        
        caso 12, 13, 14, 15, 16, 17
        Escreva ("Boa tarde!")
        
        caso 18, 19, 20, 21, 22, 23
        Escreva ("Boa noite!")
        
        outrocaso
        Escreva ("Horário invalido")
        
fimescolha


Fimalgoritmo