Algoritmo "5 homens"
//receba o sexo de 5 pessoas e pare quando houver 5 homens
Var
x, conth : inteiro
sexo: caracter


Inicio
enquanto (conth<5) faca
         escreva ("Informe seu sexo (h)-homem, (m)-mulher: ")
         leia (sexo)
         
         se (sexo = "h") entao
            conth := conth + 1
         fimse
fimenquanto
Escreva ("Número de homens: ", conth)
         


Fimalgoritmo