Algoritmo "par impar"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/04/2021
Var
num : inteiro


Inicio
Escreva ("Informe um número ")
leia (num)

se (num mod 2 = 0) entao   //mod (significa o resto da conta, número que sobrou na divisão
   Escreva ("Par ")
   
senao
     Escreva ("Impar ")

fimse


Fimalgoritmo