Algoritmo "Dolar para reais"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/03/2021
Var
dolar, convercao, reais : real


Inicio
Escreva ("Informe dinheiro em dolares : ")
Leia (dolar)
Escreva ("Informe a conversão de 1 dolar para reais ")
leia (convercao)

reais := dolar*convercao
Escreva ("A transformação de dolares para reais é ", reais)


Fimalgoritmo