Algoritmo "Equação do segundo grau"
// 
//  
// Descrição   : calcular delta
// Autor(a)    : Lucas Pontes Soares
// Data atual  : 15/03/2021
Var
a,b,c,delta: inteiro


Inicio
      escreva ("Informe o valor de a ")
      leia (a)
      escreva ("Informe o valor de b ")
      leia (b)
      escreva ("Informe o valor de c ")
      leia (c)
      
      delta:= b*b - 4*a*c
      escreva ("delta =", delta)
      


Fimalgoritmo