Algoritmo "Fahrenheit em celsius"
// 
//  
// Descrição   : conversão da temperatura  de Fahrenheit em celcius.
// Autor(a)    : Lucas Pontes Soares
// Data atual  : 15/03/2021
Var
fah, cels : real


Inicio
      escreva ("informe o valor da temperatura em Fahrenheit ")
      leia (fah)
      
      cels := (5 * (fah-32) /9)
      escreval (" A temperatura em Fahrenheit é ", fah)
      escreval (" A conversão da temperatura  de Fahrenheit em celsius é ", cels)


Fimalgoritmo