Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/03/2021
Var
// Seção de Declarações das variáveis 
peso, altura, imc : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("informe seu peso")
leia(peso)
escreva("informe sua altura")
leia(altura)
imc := peso / (altura*altura)
escreva ("O seu imc é:", imc)

Fimalgoritmo