Algoritmo "somar"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 08/03/2021
Var
valor1 : inteiro
valor2 : inteiro
soma : inteiro

Inicio
escreva("Digite o primeiro número: ")
leia(valor1)
escreva("Digite o segundo múmeor: " )
leia(valor2)

soma:= valor1 + valor2
escreva("A soma é:", soma)

Fimalgoritmo