Algoritmo "Total litros gastos"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/03/2021
Var
Km,l, media : real


Inicio
Escreva ("Informe a distancia total percorrida em Km ")
Leia (km)
Escreva ("Informe o total de litros ")
Leia (l)

media := km/l
Escreva ("A média de litros gastos é: ", media)


Fimalgoritmo