Algoritmo "Valor produto + acrescimo"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/03/2021
Var
preco, porc, valor : real


Inicio
Escreva ("Informe o preço do produto ")
leia (preco)
Escreva ("Infrome a porcentagem de acrescimo ")
leia (porc)

valor := preco * (porc/100) + preco
Escreva ("O preço do produto com acrescimo é: ", valor)


Fimalgoritmo