Algoritmo "fatorail"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/06/2021
Var
x, num, fatorial : inteiro


Inicio
fatorial := 1
Escreva ("Informe um número para realizar o fatorial: ")
leia (num)

para x de 1 ate num faca
     fatorial := fatorial * x
fimpara
Escreval (num, "! = ", fatorial)
Escreva ("Ou fatorail de ", num, " = ", fatorial)



Fimalgoritmo